#!/bin/bash
echo .
echo "======================================================="
echo "============ Installing RUNI-TJC ======================"
echo "======================================================="

echo .
echo "------------------------------------------------------------------"
echo "=============== Install dirs, files, utils & progs ==============="
echo "------------------------------------------------------------------"

echo .
echo "=============== Make link to install log ==============="
ln -s /var/log/raspberrypi-ua-netinst.log ~/.raspberrypi-ua-netinst.log

echo .
echo "=============== Make dir structure ==============="
mkdir -p ~/bin
mkdir -p ~/lib
mkdir -p ~/utils

echo .
echo "===== Getting Patcher from GitHub ====="
git clone git@bitbucket.org:Jody/rpi-ua-netinst-patcher-tjc.git ~/installer/patcher
chmod 0755 ~/installer/patcher/bin/setup
~/installer/patcher/bin/setup
add-repo ~/installer/patcher


#echo .
#echo "=============== Install installer utilities ==============="
git clone git@github.com:Jodes81/runi-utils-tjc.git ~/utils/installer
chmod 0755 ~/utils/installer/setup
~/utils/installer/setup
add-repo ~/utils/installer







# looooooooaaaaaaads of stuff to go in here. This is the BIG one!










echo .
echo =======================================================
echo ======== Finished Installing RUNI-TJC =================
echo =======================================================

