#!/bin/bash
echo .
echo =======================================================
echo ============ Installing RUNI-TJC ======================
echo =======================================================

echo .
echo "------------------------------------------------------------------"
echo "=============== Install dirs, files, utils & progs ==============="
echo "------------------------------------------------------------------"

echo .
echo =============== Make dir structure ===============
mkdir ~/bin
mkdir ~/lib
mkdir ~/utils

#echo .
#echo =============== Install installer utilities ===============
git clone git@github.com:Jodes81/runi-utils-tjc.git ~/utils/installer
add-repo ~/utils/installer







# looooooooaaaaaaads of stuff to go in here. This is the BIG one!










echo .
echo =======================================================
echo ======== Finished Installing RUNI-TJC =================
echo =======================================================

