#!/bin/bash
#----------------------------------------------------------
# REMEMBER: Whatever goes in here needs to be undone in 
# reverse in tjc-uninstall!!
#----------------------------------------------------------
echo .
echo "======================================================="
echo "============ Installing RUNI-TJC ======================"
echo "======================================================="

echo .
echo "=============== Make link to install log ==============="
ln -s /var/log/raspberrypi-ua-netinst.log ~/.raspberrypi-ua-netinst.log

echo .
echo "=============== Make dir structure ==============="
mkdir -p ~/lib
mkdir -p ~/tjc
mkdir -p ~/utils

echo .
echo "===== Getting Patcher from GitHub ====="
git clone git@bitbucket.org:Jody/rpi-ua-netinst-patcher-tjc.git ~/installer/patcher
chmod 0755 ~/installer/patcher/bin/setup
~/installer/patcher/bin/setup
add-repo ~/installer/patcher

#echo .
#echo "=============== Install installer utilities ==============="
git clone git@github.com:Jodes81/runi-utils-tjc.git ~/utils/installer
chmod 0755 ~/utils/installer/setup
~/utils/installer/setup
add-repo ~/utils/installer

#echo .
#echo "=============== Misc Utilities ==============="
git clone git@github.com:Jodes81/runi-tjc-utils-misc.git ~/utils/misc
chmod 0755 ~/utils/misc/setup
~/utils/misc/setup
add-repo ~/utils/misc

#echo .
#echo "=============== WiringPi ==============="
apt-get install make gcc -y
git clone https://github.com/WiringPi/WiringPi.git ~/lib/WiringPi
pushd ~/lib/WiringPi
./build
popd

#echo .
#echo "=============== Auto shutdown ==============="
git clone git@github.com:Jodes81/rpi-autoshutdown.git ~/tjc/autoshutdown
chmod 0755 ~/tjc/autoshutdown/setup
~/tjc/autoshutdown/setup
add-repo ~/tjc/autoshutdown

#echo .
#echo "=============== RPi Metrics ==============="
git clone git@github.com:Jodes81/rpi-metrics.git ~/utils/metrics
chmod 0755 ~/utils/metrics/setup
~/utils/metrics/setup
add-repo ~/utils/metrics

#echo .
#echo "=============== Play ==============="
git clone git@github.com:Jodes81/tjc-play.git ~/play
chmod 0755 ~/play/setup
~/play/setup
add-repo ~/play

#echo .
#echo "=============== Node v6.7.0 ==============="
if [ $(command -v node) ]; then
  mkdir -p ~/tmp
  pushd ~/tmp
  if [ ! -d node-v6.7.0-linux-armv6l ]; then
    apt-get install xz-utils -y
    if [ ! -f node-v6.7.0-linux-armv6l.tar.xz ]; then
      wget https://nodejs.org/dist/v6.7.0/node-v6.7.0-linux-armv6l.tar.xz
    fi
    tar -xJf node-v6.7.0-linux-armv6l.tar.xz
  fi
  cp -R node-v6.7.0-linux-armv6l/* /usr/local/
  popd
fi

#echo .
#echo "=============== TJC Core ==============="
git clone git@github.com:Jodes81/tjc-core.git ~/tjc/core
chmod 0755 ~/tjc/core/setup
~/tjc/core/setup
add-repo ~/tjc/core







echo .
echo "======================================================="
echo "======== Finished Installing RUNI-TJC ================="
echo "======================================================="

